spring:
  application:
    name: zuul-gateway

server:
  port: 8090

zuul:
  routes:
    marklogic:
      path: /marklogic/**
      serviceId: marklogic
      strip-prefix: true
    graphQL:
      path: /graphql/**
      serviceId: graphQL
      strip-prefix: true

ribon:
  eureka:
    enabled: false

marklogic:
  ribbon:
    listOfServers: localhost:8080

graphQL:
  ribbon:
    listOfServers: localhost:8081


